name: EMAR Risk Engine CI/CD

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC

jobs:
  run-emar-risk-engine:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run risk scoring engine
      run: python scripts/emar_risk_scoring.py

    - name: Commit and push updated report (if generated)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add reports/emar_risk_report.csv || true
        git commit -m "Daily update: EMAR risk report" || echo "No changes to commit"
        git push || echo "No push needed"
