name: EMAR Risk Engine CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test-and-train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Use Python 3.11 for broader compatibility

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with ruff
      run: ruff check .

    - name: Start PostgreSQL Container
      run: |
        docker run -d \
          --name pgvector_db \
          -e POSTGRES_USER=heet09 \
          -e POSTGRES_PASSWORD=heet123 \
          -e POSTGRES_DB=smartrxhub \
          -p 5432:5432 \
          pgvector/pgvector:pg13

    - name: Wait for database to be ready
      run: |
        # Wait for PostgreSQL to be ready (adjust timeout as needed)
        for i in $(seq 1 10); do
          docker exec smartrxhub-insights-db-1 pg_isready -h localhost -p 5432 -U heet09 && break
          echo "Waiting for database..."
          sleep 5
        done

    - name: Initialize database
      run: python init_db.py

    - name: Start FastAPI application
      run: uvicorn api.main:app --host 0.0.0.0 --port 8000 &

    - name: Wait for FastAPI to be ready
      run: |
        # Wait for FastAPI to be ready (adjust timeout as needed)
        for i in $(seq 1 10); do
          curl -s http://localhost:8000/ && break
          echo "Waiting for FastAPI..."
          sleep 5
        done

    - name: Simulate data and generate embeddings
      run: |
        python scripts/data_simulator.py &
        sleep 30 # Give simulator some time to send data
        python scripts/generate_embeddings.py

    - name: Train model
      run: python ml/trainer.py

    - name: List ml directory contents
      run: ls -l ml/

    - name: Run tests
      run: python -m pytest

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: emar-risk-model
        path: ml/emar_risk_model.joblib
